doh, add the path to the ts query.
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>

diff --git a/.github/workflows/fulcio-rekor-kind.yaml b/.github/workflows/fulcio-rekor-kind.yaml
--- a/.github/workflows/fulcio-rekor-kind.yaml
+++ b/.github/workflows/fulcio-rekor-kind.yaml
@@ -243,9 +243,12 @@ jobs:
     - name: Exercise TSA
       working-directory: ./src/github.com/sigstore/timestamp-authority
       run: |
-        curl ${{ env.TSA_URL }} > ts_chain.pem
+        curl ${{ env.TSA_URL }}/api/v1/timestamp/certchain > ts_chain.pem
         echo "myblob" > myblob
-        ./timestamp-cli --timestamp_server ${{ env.TSA_URL }} timestamp --hash sha256 --artifact myblob --out response.tsr
+        if ! ./timestamp-cli --timestamp_server ${{ env.TSA_URL }} timestamp --hash sha256 --artifact myblob --out response.tsr ; then
+          echo "failed to timestamp artifact"
+          exit =1
+        fi
         if ! ./timestamp-cli verify --timestamp response.tsr --artifact "myblob" --cert-chain ts_chain.pem ; then
           echo "failed to verify timestamp"
           exit -1
